[metadata]
  name = "mldht-composition"
  author = "Nikos Fotiou"

[global]
  plan = "mldht-test"
  case = "store-lookup"
  total_instances = 4
  builder = "docker:go"
  runner = "local:docker"

[[groups]]
  id = "providers"
  [groups.instances]
    count = 2
    percentage = 0.0

  [groups.run]
    [groups.run.test_params]
      timeout_secs = "600"

[[groups]]
  id = "searchers"
  [groups.instances]
    count = 2
    percentage = 0.0

  [groups.run]
    [groups.run.test_params]
      timeout_secs = "600"
