[metadata]
  name = "mldht-composition"
  author = "Nikos Fotiou"

[global]
  plan = "mldht-test"
  case = "dht-case"
  total_instances = 30
  builder = "docker:go"
  runner = "local:docker"
  timeout_secs = "600"

[[groups]]
  id = "nodes"
  [groups.instances]
    percentage = 1.0
